### ISSUE TITLE
在线阅读指向的域名已经过期

### ISSUE THREAD

**Issue by tamarous** [Elvenisboy/RNBook#1]
如题，网站已经打不开了。您写的这本书很不错，我之前看过几章，非常清晰明了，希望您有空可以维护一下，谢谢。

**Comment by poria-cat** [comment]
@tamarous  啊哈，时间过的总是那么快😃，我已经更新了链接，请放心食用😉

**Comment by tamarous** [comment]
### 一个小错误

第六章存储-第二节Realm-Schema
> 不出意外的话，下边会有一个黄色的提示（前边的章节有说过），先不要管它，我们一会儿解决。 为了储存数据，我们需要把输入的文字放到state里面，上面的onChangeText就是干这个的，对了，别忘记加一个叫title的状态：

```
 constructor(props) {
        super(props);
        this.state = {
              text: null
        };
 }
```

text应为title
 
### 一个小建议
可否将一些例子的完整源代码贴出来？因为您在书中讲述某个知识点时，大部分时候都是只展示与这个知识点有关的代码片段，但是一些我这样的小白能看明白每个部分，但是仍然不知道这些部分该如何组合，某个函数应该放在什么位置，因此若是有源代码可以对照着看，可能效果会好些。

**Comment by poria-cat** [comment]
@tamarous   ok，已经修改过来了(* ॑꒳ ॑* )⋆*，另外要感谢您的建议。不过由于写了太久的缘故之前的代码已经遗失了Orz，很是抱歉。至于函数的位置，只要按照书中的顺序来写就可以了（写的时候基本没怎么跳脱）。另外如果在参考小书写代码的时候觉得有问题的话随时可以问我哟( ๑´•ω•)۶
