### ISSUE TITLE
关于react-navigation的问题

### ISSUE THREAD

**Issue by pyphp** [Elvenisboy/RNBook#2]
网络上虽然各种StackNavigator 和TabNavigator的教程 但是却没有一个讲这两个同时使用的，同时使用会有很多问题，希望大神能写个同时使用的教程指点一下

**Comment by poria-cat** [comment]
emmm，抱歉啦，因为最近忙着考研的缘故只能写写简单的代码，木有时间写教程了(･_･;，真的是不好意思呐
